### ISSUE TITLE
Publish error

### ISSUE THREAD

**Issue by T0T0RO** [Kengic/DinkToPdfCopyDependencies#1]
Hi!
I had a problem using this in a .Net Core project (Visual Studio 2017).
In the dinktopdfincludesdependencies.nuspec file there is only the DinkToPdf.dll in references so when I publish my stuff to an IIS in the inetpub/site folder does not contain libwkhtmltox.dll.
When I place <reference file="libwkhtmltox.dll" /> into the references section then libwkhtmltox.dll appears in the Dependencies > NuGet > DinkToPdfIncludesDependencies (1.0.8) section of the project in Solution Explorer. So it will be included when I publish.

**Comment by leisurelyclouds** [comment]
<file src="build\**" target="build" />

**Comment by leisurelyclouds** [comment]
`<file src="build\**" target="build" />`
will copy libwkhtmltox.dll libwkhtmltox.so libwkhtmltox.dylib
I test asp.net core project and console project in vs 2017 preview cannot reproduce this issue.
are you add NuGet package DinkToPdfCopyDependencies?

**Comment by T0T0RO** [comment]
Yup. I added that NuGet package.
Something went off on my side.
I had this feeling this morning not to trust VS 2017 at all and try some basic "fix the working stuff/ have you tried to plug it in" kind of approach.
So I tried to remove and add it again and now it works just fine.
Sorry for bothering you!
